return {
	'constant/falso',
	'string/surrogate-double1st',
	'string/surrogate-double2nd',
	'string/surrogate-notpair1',
	'string/surrogate-notpair2',
	'string/surrogate-only1st',
	'string/surrogate-only2nd',
	'string/unicode-literal-hex',
	'number/0-period',
	'number/hex',
	'number/num-e',
	'number/num-period',
	'number/period-num',
	'number/plusminus',
}
