return {
	'array/0space',
	'array/empty',
	'array/space',
	'number/0',
	'number/0e',
	'number/0p0e',
	'number/mininteger',
	'number/mininteger-f',
	'object/empty',
	'string/backslash',
	'string/surrogate',
	'sample',
	'simple',
}
