return {
	'0e',
	'0p0e',
	'0space',
	'backslash',
	'emptyarray',
	'emptyobject',
	'mininteger',
	'mininteger-f',
	'regarded-as-rest-digits',
	'regarded-as-rest-eperiod',
	'regarded-as-rest-period',
	'regarded-as-rest-plus',
	'sample',
	'surrogate',
	'zero',
}
